hotreload_theme = true
force_keyboard_focus = true
theme = "default"
theme_location = ["~/.config/walker/themes/"]
additional_theme_location = "~/.config/walker/themes/"

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
next = ["ctrl j"]
previous = ["ctrl k"]
quick_activate = []

[providers]
default = [
  "desktopapplications",
  "menus",
  "windows",
  "websearch",
]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = ";"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix = "$"
provider = "windows"
